Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,6 @@
 # Use the latest 2.1 version of CircleCI pipeline process engine.
 # See: https://circleci.com/docs/configuration-reference
 version: 2.1
-
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/configuration-reference/#jobs
 jobs:
@@ -22,6 +21,8 @@ jobs:
           command:  |
             if [ << parameters.deploy_env >> == prod ] && [ "$CIRCLE_BRANCH" == "circleci-project-setup" ]; then
                 circleci-agent step halt
+                echo "Error!" 1>&2
+                exit 64
             fi
       - run:
           name: "Say hello"
