Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,7 +21,7 @@ jobs:
           command:  |
             if [ << parameters.deploy_env >> == prod ] && [ "$CIRCLE_BRANCH" == "circleci-project-setup" ]; then
                 circleci-agent step halt
-                echo "Error!" 1>&2
+                echo "You are deploying production environment with invalid branch(Require branch: release) !" 1>&2
                 exit 64
             fi
       - run:
